---
- hosts: all
  become: yes
  vars:
    docker_image: "zizou91/woc_app:latest"
    container_name: "server-container"

  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest
        update_cache: yes

    - name: Install EPEL repository
      amazon.aws.ec2_extras:
        state: present
        name: epel

    - name: Install required packages
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add Docker repository
      command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install Docker CE
      yum:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Pull Docker image from registry
      community.docker.docker_image:
        name: "{{ docker_image }}"
        source: pull
        force_source: yes

    - name: Run Docker container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        state: started
        recreate: yes
        env:
          DB_HOST: mongodb
          DB_NAME: posts
          DB_PASSWORD: abcd
          DB_PORT: "27017"
          DB_USER: root
          MONGODB_DATABASE: posts
          MONGODB_DOCKER_PORT: "27017"
          MONGODB_LOCAL_PORT: "7017"
          MONGODB_PASSWORD: abcd
          MONGODB_USER: root
          NODE_DOCKER_PORT: "8080"
          NODE_LOCAL_PORT: "6868"
        published_ports:
          - "8080:8080"