---
- hosts: all
  become: yes
  vars:
    jenkins_home: /var/lib/jenkins
    jenkins_user: jenkins
    jenkins_group: jenkins

  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest

    - name: Install required dependencies
      yum:
        name:
          - java-17-amazon-corretto
          - wget
          - git

    - name: Download Jenkins repo file
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
        mode: 0644

    - name: Import Jenkins GPG key
      rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
        state: present

    - name: Install Jenkins
      yum:
        name: jenkins
        state: latest
        update_cache: yes

    - name: Create Jenkins user
      user:
        name: jenkins
        shell: /bin/bash
        home: "{{ jenkins_home }}"
        system: yes

    - name: Set Jenkins directory permissions
      file:
        path: "{{ jenkins_home }}"
        owner: jenkins
        group: jenkins
        mode: '0755'
        state: directory

    - name: Start Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: yes
      register: jenkins_service_status
      ignore_errors: yes

    - name: Check Jenkins service status
      command: systemctl status jenkins.service
      register: service_status
      ignore_errors: yes
      when: jenkins_service_status.failed

    - name: Display Jenkins service status
      debug:
        var: service_status.stdout_lines
      when: jenkins_service_status.failed

    - name: Check Jenkins logs
      command: journalctl -u jenkins -n 50
      register: jenkins_logs
      when: jenkins_service_status.failed

    - name: Display Jenkins logs
      debug:
        var: jenkins_logs.stdout_lines
      when: jenkins_service_status.failed

    - name: Start and enable Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: yes

    - name: Wait for Jenkins to start up
      wait_for:
        port: 8080
        delay: 30
        timeout: 300

    - name: Get initial admin password
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_admin_password
      changed_when: false

    - name: Display Jenkins initial admin password
      debug:
        var: jenkins_admin_password.stdout

# Optional playbook to install additional plugins
- hosts: jenkins_servers
  become: yes
  become_user: jenkins
  vars:
    jenkins_cli_path: /var/lib/jenkins/jenkins-cli.jar
    jenkins_url: http://localhost:8080

  tasks:
    - name: Download Jenkins CLI
      get_url:
        url: http://localhost:8080/jnlpJars/jenkins-cli.jar
        dest: "{{ jenkins_cli_path }}"
        owner: jenkins
        group: jenkins
        mode: 0644

    - name: Install suggested plugins
      command: >
        java -jar {{ jenkins_cli_path }} 
        -s {{ jenkins_url }} 
        install-plugin 
        git github workflow-aggregator credentials-binding

  handlers:
    - name: Restart Jenkins
      systemd:
        name: jenkins
        state: restarted